import { StyleSheet } from '@react-pdf/renderer';

export const pdfColors = {
  accent: '#0e7490',
  text: '#0f1419',
  textSoft: '#334155',
  muted: '#64748b',
  border: '#cbd5e1',
  panel: '#f8fafc',
  warn: '#b45309',
  fatal: '#991b1b',
} as const;

export const pdfStyles = StyleSheet.create({
  page: {
    paddingTop: 28,
    paddingBottom: 36,
    paddingHorizontal: 32,
    fontFamily: 'Helvetica',
    fontSize: 9,
    lineHeight: 1.35,
    color: pdfColors.text,
    backgroundColor: '#ffffff',
  },
  footer: {
    position: 'absolute',
    bottom: 16,
    left: 32,
    right: 32,
    flexDirection: 'row',
    justifyContent: 'space-between',
    fontSize: 7,
    color: pdfColors.muted,
    borderTopWidth: 1,
    borderTopColor: pdfColors.border,
    paddingTop: 6,
  },
  eyebrow: {
    fontSize: 7,
    fontWeight: 700,
    color: pdfColors.accent,
    textTransform: 'uppercase',
    letterSpacing: 1.2,
    marginBottom: 4,
  },
  heroName: {
    fontSize: 22,
    fontWeight: 700,
    color: '#0f172a',
    marginBottom: 2,
  },
  subtitle: {
    fontSize: 10,
    fontWeight: 600,
    color: pdfColors.textSoft,
    marginBottom: 8,
  },
  heroRow: {
    flexDirection: 'row',
    gap: 16,
    marginBottom: 12,
    paddingBottom: 10,
    borderBottomWidth: 2,
    borderBottomColor: pdfColors.accent,
  },
  heroMain: { flex: 1 },
  heroAside: { width: 150 },
  section: { marginTop: 12, marginBottom: 4 },
  sectionTitle: {
    fontSize: 11,
    fontWeight: 700,
    color: pdfColors.accent,
    marginBottom: 6,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
  },
  subheading: {
    fontSize: 9,
    fontWeight: 700,
    marginTop: 8,
    marginBottom: 4,
    color: pdfColors.textSoft,
  },
  row2: { flexDirection: 'row', gap: 10 },
  col: { flex: 1 },
  panel: {
    borderWidth: 1,
    borderColor: pdfColors.border,
    backgroundColor: pdfColors.panel,
    padding: 8,
    borderRadius: 2,
    marginBottom: 6,
  },
  panelTitle: {
    fontSize: 8,
    fontWeight: 700,
    textTransform: 'uppercase',
    color: pdfColors.muted,
    marginBottom: 6,
  },
  fieldLabel: {
    fontSize: 7,
    fontWeight: 700,
    textTransform: 'uppercase',
    color: pdfColors.muted,
    marginBottom: 2,
  },
  fieldValue: { fontSize: 9, marginBottom: 6 },
  fieldBonus: { fontSize: 8, color: pdfColors.accent, marginTop: -4, marginBottom: 6 },
  muted: { fontSize: 8, color: pdfColors.muted, fontStyle: 'italic' },
  metaRow: { flexDirection: 'row', gap: 6, marginBottom: 2 },
  metaLabel: { fontSize: 7, fontWeight: 700, color: pdfColors.muted, width: 56 },
  metaValue: { fontSize: 8.5, flex: 1 },
  quickLabel: { fontSize: 7, fontWeight: 700, color: pdfColors.muted, textTransform: 'uppercase' },
  quickValue: { fontSize: 14, fontWeight: 700, marginBottom: 4 },
  stressRow: { flexDirection: 'row', gap: 3, flexWrap: 'wrap' },
  stressBox: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: pdfColors.accent,
  },
  stressBoxFilled: { backgroundColor: pdfColors.accent },
  badgeRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 6 },
  badge: {
    fontSize: 7,
    paddingVertical: 2,
    paddingHorizontal: 4,
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: 2,
  },
  badgeWarn: { borderColor: pdfColors.warn, color: pdfColors.warn },
  badgeOk: { borderColor: '#15803d', color: '#15803d' },
  tickRow: { flexDirection: 'row', gap: 3 },
  tick: {
    width: 8,
    height: 8,
    borderRadius: 4,
    borderWidth: 1,
    borderColor: pdfColors.accent,
  },
  tickFilled: { backgroundColor: pdfColors.accent },
  attrHead: {
    fontSize: 7,
    fontWeight: 700,
    color: pdfColors.accent,
    textTransform: 'uppercase',
    marginTop: 4,
    marginBottom: 2,
  },
  actionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e2e8f0',
  },
  actionName: { fontSize: 8.5 },
  actionRating: { fontSize: 8.5, fontWeight: 700, color: pdfColors.accent },
  harmTitle: { fontSize: 8, fontWeight: 700, marginBottom: 4 },
  harmBox: {
    flexDirection: 'row',
    gap: 6,
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 4,
    marginBottom: 3,
  },
  harmLevel: { width: 52, fontSize: 8, fontWeight: 700 },
  harmHint: { fontSize: 6.5, color: pdfColors.muted, fontWeight: 400 },
  harmText: { flex: 1, fontSize: 8 },
  harmFatal: {
    borderColor: pdfColors.fatal,
    backgroundColor: '#fef2f2',
    color: pdfColors.fatal,
    fontWeight: 700,
    padding: 4,
    fontSize: 8,
    marginBottom: 3,
  },
  xpTrack: { marginBottom: 5 },
  xpHead: { flexDirection: 'row', justifyContent: 'space-between', fontSize: 8, marginBottom: 2 },
  xpBoxes: { flexDirection: 'row', gap: 2 },
  xpBox: {
    width: 10,
    height: 10,
    borderWidth: 1,
    borderColor: pdfColors.border,
  },
  xpBoxOn: { backgroundColor: pdfColors.accent, borderColor: pdfColors.accent },
  inlineStat: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: 4 },
  scarRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 4, marginTop: 4 },
  tag: {
    fontSize: 7,
    paddingVertical: 2,
    paddingHorizontal: 5,
    borderWidth: 1,
    borderColor: pdfColors.border,
    borderRadius: 2,
  },
  tagOn: { backgroundColor: '#ecfeff', borderColor: pdfColors.accent, color: pdfColors.accent },
  connCard: {
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 6,
    marginBottom: 5,
    width: '48%',
  },
  connGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  connHead: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 3 },
  gearItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingVertical: 2,
    borderBottomWidth: 0.5,
    borderBottomColor: '#e2e8f0',
  },
  quirkGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 6 },
  quirk: {
    width: '31%',
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 5,
    marginBottom: 4,
  },
  quirkSpent: { opacity: 0.55 },
  abilityCard: {
    borderWidth: 1,
    borderColor: pdfColors.border,
    padding: 6,
    marginBottom: 5,
    width: '48%',
  },
  abilityPrimary: { borderColor: pdfColors.accent, backgroundColor: '#ecfeff' },
  abilityTag: { fontSize: 6.5, color: pdfColors.accent, fontWeight: 700, marginBottom: 2 },
  abilityDesc: { fontSize: 7.5, color: pdfColors.textSoft, marginTop: 3 },
  driveRow: { flexDirection: 'row', gap: 12, marginTop: 6 },
  notes: { fontSize: 8.5, color: pdfColors.textSoft },
});
